---
title: "Inference in Gaussian Process Models for Political Science"
author: "JBrandon Duck-Mayr"
date: "`r quack::american_date_format(Sys.Date())`"
abstract: "Abstract (typically should be 150 words or less)"
anonymized: true
wordcount: "XXXX"
bibliography: "gp-inference-refs.bib"
nocite: "@*"
output: quack::submission
editor_options:
  markdown:
    wrap: sentence
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction

Political scientists are increasingly mindful of the danger of misspecification bias [@HainmuellerHazlett2014], particularly regarding interactive effects [@BeiserMcGrathBeiserMcGrath2023; @BlackwellOlson2022; @HainmuellerEtAl2019; @ZhirnovEtAl2023].
A number of approaches to this problem have been proposed, including diagnostic tests [@HainmuellerEtAl2019] and modeling strategies [@BlackwellOlson2022; @HainmuellerHazlett2014].
Some political scientists have begun using Gaussian process (GP) regression, a model from the machine learning literature, in situations where misspecification bias or correlated errors are a concern [@CarlsonND; @ChenEtAl2023; @DuckMayrEtAl2020; @Gill2021; @MonoganGill2016].
However, as GP models were developed by computer scientists, most existing treatments of GP regression and classification [e.g. @RasmussenWilliams2006] focus on prediction rather than inference.
I derive the distribution of average marginal effects for GP regression and classification, and present a guide for political scientists on performing inference using these models.[^1]
(I have developed an R package, `gpmss`, that implements these techniques and provides a user-friendly interface similar to the familiar basic functions for general linear models in R.)
I then compare GP regression and classification against other methods of guarding against misspecification bias in a simulation study.[^2]
Finally, I illustrate the use of GP regression and classification models in two real-world applications.

[^1]: See @HainmuellerHazlett2014 for a similar treatment of the Kernel Regulated Least Squares model.

[^2]: All analysis in this paper was conducted in R [@R] using RStudio [@RStudio].

<!-- Add a more detailed section on the problem(s) of misspecification bias
     (and correlated errors)? -->

# An Introduction to Gaussian Process Models

As social scientists, we are typically interested in the relationship $f$ between a set of explanatory variables $X$ and outcomes $y$ that are realized with some noise $\varepsilon$; that is, $y = f(X) + \varepsilon$ and we want to learn about $f$.
The standard approach in political science is to assume a functional form for $f$ and perform inference on its parameters.
However, in many contexts faced by political scientists, we should admit more uncertainty about the function form of $f$; many assumptions we often make such as linearity or which interactive or second (or third...) order terms to include may be unfounded [@HainmuellerHazlett2014; @HainmuellerEtAl2019].

GP regression and classification takes a different approach: We place a prior distribution over $f$ and derive the posterior distribution after obtaining observations of the predictors, $\mathbf{X}$, and observations of the outcomes, $\mathbf{y}$.
Placing a prior distribution over a function is likely a novel concept for most political scientists, but it will become clear after a brief discussion of what a Gaussian process is.
A Gaussian process is an infinite dimensional generalization of the normal distribution, where any finite subcollection 

# Inference for Quantities of Interest

# Comparison to Other Methods

# Applications

# Conclusion

# References
